package com.bb.apps.myapp.server;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Authenticator;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
public class SendEmailUtil {
  public static void sendAnEmail(String args) {
     
	 Logger log = LoggerFactory.getLogger(SendEmailUtil.class);
	  
     Properties props = System.getProperties();
     /*props.setProperty("mail.smtp.host", "smtp.gmail.com");
     props.setProperty("mail.smtp.port", "587");
     props.put("mail.smtp.starttls","true");
     props.put("mail.smtp.auth", "true");
     props.put("mail.debug", "true");
     props.put("mail.smtp.connectiontimeout", 1000);*/
     props.put("mail.smtp.host", "smtp.gmail.com");  
     props.put("mail.smtp.socketFactory.port", "587");  
     props.put("mail.smtp.socketFactory.class",  
               "javax.net.ssl.SSLSocketFactory");  
     props.put("mail.smtp.auth", "true");  
     props.put("mail.smtp.port", "587"); 
     props.put("mail.smtp.starttls.enable", "true");
     final String username = "ytactions@gmail.com";//
     final String password = "ytactions";
     try{
     Session session = Session.getDefaultInstance(props,
                          new Authenticator(){
                             protected PasswordAuthentication getPasswordAuthentication() {
                                return new PasswordAuthentication(username, password);
                             }});

     //https://www.google.com/settings/security/lesssecureapps to turn on 
     // -- Create a new message --
     Message msg = new MimeMessage(session);
     Multipart maltipart = new MimeMultipart();

     // -- Set the FROM and TO fields --
     msg.setFrom(new InternetAddress(username));
     msg.setRecipient(Message.RecipientType.TO, new InternetAddress("mr.ganeshbhandari@gmail.com"));
     msg.setSubject("MyApp : notification");
     msg.setContent(maltipart);
     
     BodyPart body1 = new MimeBodyPart();
     body1.setContent("<div style='font-size:13px;font-family:Courier New;'> "
     		+ "<p>"
     		+ "Dear Sir/Madam"
     		+ "</p>"
     		+ "<p>"
     		+ "The following MyApp request has been assigned to you. Please find the documents attached along with this mail."
     		+ "<ul>"
     		+ "<li>"
     		+ "<span style='width:120px;display:inline-block;'> Request ID  <span>: "+"123456"
     		+ "</li>"
     		+ "<li>"
     		+ "<span style='width:120px;display:inline-block;'> Request Type  <span>: "+"notification"
     		+ "</li>"
     		+ "<li>"
     		+ "<span style='width:120px;display:inline-block;'> Request initiator  <span>: "+"user"
     		+ "</li>"
     		+ "<li>"
     		+ "<span style='width:120px;display:inline-block;'> Request Date  <span>: "+"today"
     		+ "</li>"
     		+ "</ul>"
     		+ "</p>"
     		+ "<br><br><br>"
     		+ "<b>ATTENSION:</b>This mail is auyomatically generated by MyApp sysetm. Please do not reply to this mail."
     		+ "</div>","text/html");
     
     MimeBodyPart body2 = new MimeBodyPart();
     String fileName = args;
     DataSource source = new FileDataSource(fileName);
     body2.setDataHandler(new DataHandler(source));
     //body2.setFileName("myAppFile.png");
     
     maltipart.addBodyPart(body1);
     maltipart.addBodyPart(body2);
     
     Transport.send(msg);
     System.out.println("Message sent.");
     log.debug("Message Sent");
     
  }catch (MessagingException e){ 
	  System.out.println("Erreur d'envoi, cause: " + e);
	  e.printStackTrace();
	  log.error(e.getMessage());
  }
  }
  }