function com_bb_apps_myapp_MyApp_JUnit(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',ec='&',xc='.cache.html',db='/',pb='//',wc=':',tb='::',Fc='<script defer="defer">com_bb_apps_myapp_MyApp_JUnit.onInjectionDone(\'com.bb.apps.myapp.MyApp.JUnit\')<\/script>',lb='<script id="',wb='=',cb='?',yb='Bad handler "',Ec='DOMContentLoaded',vc="GWT module 'com.bb.apps.myapp.MyApp.JUnit' may need to be (re)compiled",nb='SCRIPT',hc='Unexpected exception in locale detection, using default: ',gc='_',fc='__gwt_Locale',kb='__gwt_marker_com.bb.apps.myapp.MyApp.JUnit',_b='adobeair',ac='air',ob='base',gb='baseUrl',X='begin',W='bootstrap',Hb='chrome',fb='clear.cache.gif',U='com.bb.apps.myapp.MyApp.JUnit',ib='com.bb.apps.myapp.MyApp.JUnit.nocache.js',sb='com.bb.apps.myapp.MyApp.JUnit::',vb='content',cc='default',ab='end',Xb='gecko',Zb='gecko1_8',$b='gecko1_9',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',yc='gwt/standard/standard.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',Gb='gxt.user.agent',Dc='head',tc='hosted.html?com_bb_apps_myapp_MyApp_JUnit',Cc='href',Kb='ie10',Qb='ie6',Ob='ie7',Mb='ie8',Lb='ie9',Cb='iframe',eb='img',Db="javascript:''",zc='link',pc='linux',sc='loadExternalRefs',bc='locale',dc='locale=',oc='mac',nc='mac os x',mc='macintosh',qb='meta',Fb='moduleRequested',_='moduleStartup',Jb='msie',Pb='msie 6',Nb='msie 7',rb='name',Ib='opera',Eb='position:absolute;width:0;height:0;border:none',Ac='rel',Yb='rv:1.8',Rb='safari',Tb='safari3',Vb='safari4',Wb='safari5',hb='script',uc='selectingPermutation',V='startup',Bc='stylesheet',jb='undefined',kc='unknown',ic='user.agent',lc='user.agent.os',Sb='version/3',Ub='version/4',jc='webkit',rc='win32',qc='windows';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}com_bb_apps_myapp_MyApp_JUnit=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=K(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Hb)!=-1)return Hb;if(a.indexOf(Ib)!=-1)return Ib;if(a.indexOf(Jb)!=-1){if(n.documentMode>=10)return Kb;if(n.documentMode>=9)return Lb;if(n.documentMode>=8)return Mb;if(a.indexOf(Nb)!=-1)return Ob;if(a.indexOf(Pb)!=-1)return Qb;return Kb}if(a.indexOf(Rb)!=-1){if(a.indexOf(Sb)!=-1)return Tb;if(a.indexOf(Ub)!=-1)return Vb;return Wb}if(a.indexOf(Xb)!=-1){if(a.indexOf(Yb)!=-1)return Zb;return $b}if(a.indexOf(_b)!=-1)return ac;return null};v[Gb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};w[bc]=function(){var b=null;var c=cc;try{if(!b){var d=location.search;var e=d.indexOf(dc);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(ec,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(bc)}if(!b){b=m[fc]}if(b){c=b}while(b&&!J(bc,b)){var h=b.lastIndexOf(gc);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(hc+a)}m[fc]=c;return b||cc};v[bc]={de:0,'default':1,hi_IN:2,kn_IN:3};w[ic]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(jc)!=-1}())return Rb;if(function(){return b.indexOf(Jb)!=-1&&n.documentMode>=10}())return Kb;if(function(){return b.indexOf(Jb)!=-1&&n.documentMode>=9}())return Lb;if(function(){return b.indexOf(Jb)!=-1&&n.documentMode>=8}())return Mb;if(function(){return b.indexOf(Xb)!=-1}())return Zb;return kc};v[ic]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};w[lc]=function(){var a=m.navigator.userAgent.toLowerCase();if(a.indexOf(mc)!=-1||a.indexOf(nc)!=-1){return oc}if(a.indexOf(pc)!=-1){return pc}if(a.indexOf(qc)!=-1||a.indexOf(rc)!=-1){return qc}return kc};v[lc]={linux:0,mac:1,unknown:2,windows:3};com_bb_apps_myapp_MyApp_JUnit.onScriptLoad=function(){if(M){r=true;G()}};com_bb_apps_myapp_MyApp_JUnit.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:sc,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=tc;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:uc});if(!F()){try{alert(vc);return;var Q=O.indexOf(wc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+xc}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[yc]){var a=n.createElement(zc);__gwt_stylesLoaded[yc]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,t+yc);n.getElementsByTagName(Dc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Ec,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(Ec,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:sc,millis:(new Date).getTime(),type:X});n.write(Fc)}
com_bb_apps_myapp_MyApp_JUnit();