function MyApp(){var db='',ab=' top: -1000px;',Ab='" for "gwt:onLoadErrorFn"',yb='" for "gwt:onPropertyErrorFn"',jb='");',Bb='#',ic='&',Ac='.cache.js',Db='/',Jb='//',zc=':',sb='::',Nc=':moduleBase',cb='<!doctype html>',eb='<html><head><\/head><body><\/body><\/html>',vb='=',Cb='?',xb='Bad handler "',bb='CSS1Compat',hb='Chrome',gb='DOMContentLoaded',X='DUMMY',yc="GWT module 'MyApp' may need to be (re)compiled",Mc='Ignoring non-whitelisted Dev Mode URL: ',V='MyApp',xc='MyApp.devmode.js',Hb='MyApp.nocache.js',rb='MyApp::',lc='Unexpected exception in locale detection, using default: ',kc='_',Lc='__gwtDevModeHook:MyApp',jc='__gwt_Locale',Kc='_gwt_dummy_',dc='adobeair',ec='air',Ib='base',Gb='baseUrl',S='begin',Y='body',R='bootstrap',Lb='chrome',Fb='clear.cache.gif',ub='content',gc='default',Hc='end',ib='eval("',Jc='file:',_b='gecko',bc='gecko1_8',cc='gecko1_9',T='gwt.codesvr.MyApp=',U='gwt.codesvr=',Gc='gwt/standard/standard.css',zb='gwt:onLoadErrorFn',wb='gwt:onPropertyErrorFn',tb='gwt:property',Kb='gxt.user.agent',ob='head',Ec='href',Ic='http:',Ob='ie10',Ub='ie6',Sb='ie7',Qb='ie8',Pb='ie9',Z='iframe',Eb='img',lb='javascript',$='javascript:""',Bc='link',tc='linux',Fc='loadExternalRefs',fc='locale',hc='locale=',sc='mac',rc='mac os x',qc='macintosh',pb='meta',nb='moduleRequested',mb='moduleStartup',Nb='msie',Tb='msie 6',Rb='msie 7',qb='name',Mb='opera',_='position:absolute; width:0; height:0; border:none; left: -1000px;',Cc='rel',ac='rv:1.8',Vb='safari',Xb='safari3',Zb='safari4',$b='safari5',kb='script',wc='selectingPermutation',W='startup',Dc='stylesheet',fb='undefined',oc='unknown',mc='user.agent',pc='user.agent.os',Wb='version/3',Yb='version/4',nc='webkit',vc='win32',uc='windows';var p=window;var q=document;s(R,S);function r(){var a=p.location.search;return a.indexOf(T)!=-1||a.indexOf(U)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:V,sessionId:p.__gwtStatsSessionId,subSystem:W,evtGroup:a,millis:(new Date).getTime(),type:b})}}
MyApp.__sendStats=s;MyApp.__moduleName=V;MyApp.__errFn=null;MyApp.__moduleBase=X;MyApp.__softPermutationId=0;MyApp.__computePropValue=null;MyApp.__getPropMap=null;MyApp.__gwtInstallCode=function(){};MyApp.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[V]={moduleName:V};var w;function A(){C();return w}
function B(){C();return w.getElementsByTagName(Y)[0]}
function C(){if(w){return}var a=q.createElement(Z);a.src=$;a.id=V;a.style.cssText=_+ab;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function D(k){function l(a){function b(){if(typeof q.readyState==fb){return typeof q.body!=fb&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=B();var f=A();var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(ib));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(jb));g=f.createElement(kb);g.language=lb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(kb);g.language=lb;g.text=c[i];e.appendChild(g);d(e,g)}}}
MyApp.onScriptDownloaded=function(a){l(function(){m(a)})};s(mb,nb);var n=q.createElement(kb);n.src=k;q.getElementsByTagName(ob)[0].appendChild(n)}
MyApp.__startLoadingFragment=function(a){return H(a)};MyApp.__installRunAsyncCode=function(a){var b=B();var c=A().createElement(kb);c.language=lb;c.text=a;b.appendChild(c);b.removeChild(c)};function F(){var c={};var d;var e;var f=q.getElementsByTagName(pb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,db);if(j.indexOf(sb)>=0){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=db}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;MyApp.__errFn=e}
function G(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=0?a.substring(0,d+1):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=u(Gb);if(a!=null){return a}return db}
function h(){var a=q.getElementsByTagName(kb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return db}
function i(){var a=q.getElementsByTagName(Ib);if(a.length>0){return a[a.length-1].href}return db}
function j(){var a=q.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(q.location.href)}k=f(k);return k}
function H(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return MyApp.__moduleBase+a}
function I(){var i=[];var j=0;var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
l[Kb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1)return Mb;if(a.indexOf(Nb)!=-1){if(q.documentMode>=10)return Ob;if(q.documentMode>=9)return Pb;if(q.documentMode>=8)return Qb;if(a.indexOf(Rb)!=-1)return Sb;if(a.indexOf(Tb)!=-1)return Ub;return Ob}if(a.indexOf(Vb)!=-1){if(a.indexOf(Wb)!=-1)return Xb;if(a.indexOf(Yb)!=-1)return Zb;return $b}if(a.indexOf(_b)!=-1){if(a.indexOf(ac)!=-1)return bc;return cc}if(a.indexOf(dc)!=-1)return ec;return null};k[Kb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};l[fc]=function(){var b=null;var c=gc;try{if(!b){var d=location.search;var e=d.indexOf(hc);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(ic,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=u(fc)}if(!b){b=p[jc]}if(b){c=b}while(b&&!t(fc,b)){var h=b.lastIndexOf(kc);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(lc+a)}p[jc]=c;return b||gc};k[fc]={de:0,'default':1,hi_IN:2,kn_IN:3};l[mc]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(nc)!=-1}())return Vb;if(function(){return b.indexOf(Nb)!=-1&&q.documentMode>=10}())return Ob;if(function(){return b.indexOf(Nb)!=-1&&q.documentMode>=9}())return Pb;if(function(){return b.indexOf(Nb)!=-1&&q.documentMode>=8}())return Qb;if(function(){return b.indexOf(_b)!=-1}())return bc;return oc};k[mc]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};l[pc]=function(){var a=p.navigator.userAgent.toLowerCase();if(a.indexOf(qc)!=-1||a.indexOf(rc)!=-1){return sc}if(a.indexOf(tc)!=-1){return tc}if(a.indexOf(uc)!=-1||a.indexOf(vc)!=-1){return uc}return oc};k[pc]={linux:0,mac:1,unknown:2,windows:3};t=function(a,b){return b in k[a]};MyApp.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};MyApp.__computePropValue=m;p.__gwt_activeModules[V].bindings=MyApp.__getPropMap;s(R,wc);if(r()){return H(xc)}var n;try{alert(yc);return;var o=n.indexOf(zc);if(o!=-1){j=parseInt(n.substring(o+1),10);n=n.substring(0,o)}}catch(a){}MyApp.__softPermutationId=j;return H(n+Ac)}
function J(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=q.createElement(Bc);b.setAttribute(Cc,Dc);b.setAttribute(Ec,H(a));q.getElementsByTagName(ob)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
s(Fc,S);c(Gc);s(Fc,Hc)}
F();MyApp.__moduleBase=G();v[V].moduleBase=MyApp.__moduleBase;var K=I();if(p){var L=!!(p.location.protocol==Ic||p.location.protocol==Jc);p.__gwt_activeModules[V].canRedirect=L;function M(){var b=Kc;try{p.sessionStorage.setItem(b,b);p.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(L&&M()){var N=Lc;var O=p.sessionStorage[N];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(O)){if(O&&(window.console&&console.log)){console.log(Mc+O)}O=db}if(O&&!p[N]){p[N]=true;p[N+Nc]=G();var P=q.createElement(kb);P.src=O;var Q=q.getElementsByTagName(ob)[0];Q.insertBefore(P,Q.firstElementChild||Q.children[0]);return false}}}J();s(R,Hc);D(K);return true}
MyApp.succeeded=MyApp();